# NOTE: This configuration file is not used by drone.io but as a backup file.

# BEFORE
# ======
# Switch to GCC 4.8 to have the C++11 support
echo 2 | sudo update-alternatives --config gcc
# Root path
ROOT=`pwd`

# INSTALL
# =======
mkdir -p _opt/cmake
cd _opt/cmake
# CMake 3.1 or later is needed but drone.io still uses CMake 2.8.7
mkdir cmake
wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.sh >> /dev/null 2>&1
sh cmake-3.2.3-Linux-x86_64.sh --skip-license
# Download a recent version of Doxygen
cd ..
wget http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.9.1.linux.bin.tar.gz >> /dev/null 2>&1
mkdir doxygen && tar -zxvf doxygen-1.8.9.1.linux.bin.tar.gz -C doxygen --strip-components 1 >> /dev/null 2>&1
DOXYGEN_EXECUTABLE="$ROOT/_opt/doxygen/bin/doxygen"

# SCRIPT
# ======
cd ..
mkdir _build
cd _build
# Download the data used for the unit test
git clone https://github.com/Biomechanical-ToolKit/BTKData.git Testing/Data
# Configure
$ROOT/_opt/cmake/bin/cmake -DCMAKE_BUILD_TYPE:CHAR=Release -DBUILD_SHARED_LIBS:BOOL=1 -DBUILD_DOCUMENTATION_API:BOOL=1 -DDOXYGEN_EXECUTABLE:FILEPATH=$DOXYGEN_EXECUTABLE -DBUILD_TESTING:BOOL=1 -DBTK_TESTING_DATA_PATH:CHAR=$ROOT/_build/Testing/Data -G "Unix Makefiles" ..
# Compile
make
# Test
$ROOT/_opt/cmake/bin/ctest -VV
