# NOTE: This configuration file is not used by drone.io but as a backup file.

# Switch to GCC 4.8 to have the C++11 support
echo 2 | sudo update-alternatives --config gcc
# Temporary forlder for the building job
mkdir build
cd build
ROOT=`pwd`
# CMake 3.1 or later is needed but drone.io still uses CMake 2.8.7
wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.sh >> /dev/null 2>&1
sudo sh cmake-3.2.3-Linux-x86_64.sh --skip-license
# Download the data used for the unit test
git clone https://github.com/Biomechanical-ToolKit/BTKData.git Testing/Data
# Configure
$ROOT/bin/cmake -DCMAKE_BUILD_TYPE:CHAR=Release -DBUILD_SHARED_LIBS:BOOL=1 -DBUILD_TESTING:BOOL=1 -DBTK_TESTING_DATA_PATH:CHAR=$ROOT/Testing/Data -G "Unix Makefiles" ..
# Compile
make
# Test
$ROOT/bin/ctest -VV
