#include "_TDDConfigure.h"

#include "Common/AnyTest.h"
// #include "AcquisitionTest.h"
// #include "AnalogTest.h"
#include "Common/EventTest.h"
// #include "ForcePlatformTypesTest.h"
// #include "IMUTypesTest.h"
// #include "Common/CowodPtrTest.h"
#include "Common/ObjectTest.h"
#include "Common/LoggerTest.h"
// #include "PointTest.h"
// #include "PointCollectionTest.h"
// #include "MetaDataInfoTest.h"
// #include "MetaDataTest.h"
#include "Common/NodeTest.h"
// #include "PipelineTest.h"
#include "Common/TimeSequenceTest.h"
// #include "TriangleMeshTest.h"