#include "_TDDConfigure.h"

#include "AcquisitionUnitConverterTest.h"
#include "ForcePlatformsExtractorTest.h"
#include "ForcePlatformWrenchFilterTest.h"
#include "GroundReactionWrenchFilterTest.h"
#include "IMUsExtractorTest.h"
#include "MeasureFrameExtractorTest.h"
#include "MergeAcquisitionFilterTest.h"
#include "SeparateKnownVirtualMarkersFilterTest.h"
#include "SpecializedPointsExtractorTest.h"
#include "VerticalGroundReactionForceGaitEventDetectorTest.h"
#include "WrenchDirectionAngleFilterTest.h"
