#include "_TDDConfigure.h"

#include "AcquisitionTest.h"
#include "ForcePlatformTypesTest.h"
#include "PointTest.h"
#include "PointCollectionTest.h"
#include "MetaDataInfoTest.h"
#include "MetaDataTest.h"
#include "PipelineTest.h"
#include "TriangleMeshTest.h"